name: Bump version month

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set version
        id: version
        run: echo "version='$(date '+%Y').$(date '+%-m').0'" >> $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: yearly-version
          title: 'chore(release): bump version'
          body: "Release-As: ${{ steps.version.outputs.version }}"
          labels: chore,changelog
