name: Bump version year

on:
  workflow_call:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set version
        id: version
        run: echo "version=$(date '+%Y').1.0" >> $GITHUB_OUTPUT

      - name: Get GitHub App user ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Update values for git user config
        run: |
          echo "GIT_USER_NAME=${{ steps.app-token.outputs.app-slug }}[bot]" >> $GITHUB_ENV
          echo "GIT_USER_EMAIL=${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com" >> $GITHUB_ENV

      - name: Bump version
        run: |
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
          git checkout dev
          git commit --allow-empty -m "chore(release): bump version" -m "Release-As: ${{ steps.version.outputs.version }}"
          git push origin dev
