name: Publish release

on:
  workflow_call:
    inputs:
      GHA_APP_ID:
        description: 'GitHub app ID'
        required: true
    secrets:
      GHA_PRIVATE_KEY:
        description: 'GitHub app private key'
        required: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ inputs.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
